apiVersion: apps/v1
kind: Deployment
metadata:
  name: anki
  namespace: anki
  labels:
    app: anki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anki
    spec:
      containers:
        - image: registry.ssene.ca/anki-sync-server:2.3.0
          name: anki
          ports:
            - containerPort: 27701
              name: http
          env:
            - name: ANKISYNCD_HOST
              value: "0.0.0.0"
            - name: ANKISYNCD_PORT
              value: "27701"
            - name: ANKISYNCD_DATA_ROOT
              value: "./collections"
            - name: ANKISYNCD_BASE_URL
              value: "/sync/"
            - name: ANKISYNCD_BASE_MEDIA_URL
              value: "/msync/"
            - name: ANKISYNCD_AUTH_DB_PATH
              value: "./auth.db"
            - name: ANKISYNCD_SESSION_DB_PATH
              value: "./session.db"
          volumeMounts:
            - mountPath: /app/data
              name: data
              readOnly: false
            - mountPath: /opt/ankisyncd
              name: opt
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: anki-data
        - name: opt
          persistentVolumeClaim:
            claimName: anki-opt
status: {}
