apiVersion: v1
kind: PersistentVolume
metadata:
  name: anki-data
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/anki-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anki-data
  namespace: anki
spec:
  storageClassName: local-path
  volumeName: anki-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
