apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 2.3.6
      sourceRef:
        name: bitnami
        kind: HelmRepository
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.240-192.168.1.250
    controller:
      image:
        repository: bitnami/metallb-controller
        tag: 0.9.6
    speaker:
      image:
        repository: bitnami/metallb-speaker
        tag: 0.9.6
