apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: kube-system
spec:
  interval: 5m
  releaseName: intel-gpu-plugin
  chart:
    spec:
      chart: intel-gpu-plugin
      version: 4.1.0
      sourceRef:
        name: k8s-at-home
        kind: HelmRepository
  values:
    image:
      repository: intel/intel-gpu-plugin
      tag: 0.23.0
