apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: gotify
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 10.13.14
      sourceRef:
        name: bitnami
        namespace: flux-system
        kind: HelmRepository
  valuesFrom:
    - kind: Secret
      name: postgresql-credentials
  values:
    image:
      repository: bitnami/postgresql
      tag: 14.1.0
    persistence:
      existingClaim: database-gotify
    volumePermissions:
      enabled: true
    rbac:
      create: true
