apiVersion: v1
kind: PersistentVolume
metadata:
  name: gotify-data
spec:
  storageClassName: longhorn
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/gotify
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data
  namespace: gotify
spec:
  storageClassName: longhorn
  volumeName: gotify-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
