apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-gotify
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/databases/gotify
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-gotify
  namespace: gotify
spec:
  storageClassName: longhorn
  volumeName: database-gotify
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
