apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  releaseName: gitea
  chart:
    spec:
      chart: gitea
      version: 5.0.7
      sourceRef:
        name: gitea
        kind: HelmRepository
  valuesFrom:
    - kind: Secret
      name: gitea-secrets
  values:
    image:
      repository: gitea/gitea
      tag: 1.16.7
      rootless: true
    podSecurityContext:
      fsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    service:
      http:
        type: ClusterIP
        port: 3000
      ssh:
        type: LoadBalancer
        port: 22
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: git.ssene.ca
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - git.ssene.ca
          secretName: gitea-tls-cert
    persistence:
      storageClass: local-path
    gitea:
      admin:
        username: sseneca
        email: "me@ssene.ca"
      config:
        APP_NAME: "sseneca's gitea"
        RUN_MODE: prod
        repository:
          ROOT: /data/git/gitea-repositories
          PREFERRED_LICENSES: GPL-3.0-or-later,Apache-2.0,X11
          ENABLE_PUSH_CREATE_USER: true
          DEFAULT_BRANCH: main
        service:
          DISABLE_REGISTRATION: true
        security:
          PASSWORD_CHECK_PWN: true
        picture:
          DISABLE_GRAVATAR: true
          ENABLE_FEDERATED_AVATAR: true
    postgresql:
      enabled: true
      image:
        tag: 13.1.0
      persistence:
        existingClaim: database-gitea
      volumePermissions:
        enabled: true
      psp:
        create: true
      rbac:
        create: true
