apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 5m
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: 1.13.2
      sourceRef:
        name: bitnami
        kind: HelmRepository
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.16.0
