apiVersion: v1
kind: PersistentVolume
metadata:
  name: dendrite-jetstream
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi # Probably overkill, 1GB should be enough
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/dendrite-jetstream
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dendrite-jetstream
  namespace: dendrite
spec:
  storageClassName: local-path
  volumeName: dendrite-jetstream
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
