apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: prosody
  labels:
    app: prosody
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prosody
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prosody
    spec:
      containers:
        - image: registry.ssene.ca/prosody:0.12.0
          name: prosody
          ports:
            - containerPort: 5222
              name: c2s
            - containerPort: 5269
              name: s2s
          volumeMounts:
            - mountPath: /etc/prosody
              name: configuration
              readOnly: true
            - mountPath: /var/lib/prosody
              name: data
            - mountPath: /etc/prosody/certs
              name: certs
              readOnly: true
      imagePullSecrets:
        - name: sseneca
      restartPolicy: Always
      volumes:
        - name: configuration
          secret:
            secretName: configuration-secrets
        - name: data
          persistentVolumeClaim:
            claimName: prosody-media
        - name: certs
          projected:
            sources:
              - secret:
                  name: prosody-tls-cert
                  items:
                    - key: tls.crt
                      path: ssene.ca.crt
                    - key: tls.key
                      path: ssene.ca.key
              - secret:
                  name: conference-prosody-tls-cert
                  items:
                    - key: tls.crt
                      path: conference.xmpp.ssene.ca.crt
                    - key: tls.key
                      path: conference.xmpp.ssene.ca.key
status: {}
