apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgBCLkQ5ykVI2Bjrt492DNWJGegqqDVyrZ6Y5jM8uoZXjt47UxInx/BucSmmKpbEdJQWFeaQ8uZ7830UpeLe2uIbg8xISu7B1qw65RT4ASBj0uWoI4kBy9V6hGXzYT/FBxBQr9DjtrLV/9efrths5vtD7+20+JySMYrGY1vVpvkx2aDbU6jmKSFOeUCR3Rd3oxtCMwuzA4yU06wDZqpUP6oXtQx2K57zD8TAIty0VrMmGr2gc2WcqNhTjmcJFDIwSrpEZi199snn/0UNp2OP/Db+3kK/MXQswvMFEf7cAlHElyvMPmCBW7wF2VpkGEWDfvkxKR4mx9duHnpX8XO1Bxqm85GarzQQm42DmVhasK8K/OGNPYCSF0tEu5f3ZDXhzroXMx+UKy0PK26lrR8SN0ZeYOeY5KNPjxjj4YmFiKrd5ayxsGhOOfiU2G6MfL6cNyDf8weEgxXGINhLj9ksgaV1Dui6HnFUX0+VPSwWamKQh8Q+i7SixsGROE90gW2n2YM3mzG6WjnqVJhmYQ/jhGONf1HCuT9cywqYnq6n2mQbY5iUK5nk3K0OjTjEbDxO7hbl6SxAiXHvqkehDUcNCQFACzzBGfCMW07RxcM8EeuV725C19yCYK+kJzEXadsNyiUZjJ1Z98LT4YlRK3xct30Qq4Umot1+bUk7qii9fiFPwJiuOApfOFuq9vQ2BH1zrXUmfXRh+IPlEp7WoLSZh9rvWvA28t9EiLyXWVSm8bPvvQMP3w971mFZWXsXwZXT7wgCYdJJPSZxTyIif8KdO0puKanO/gExE6/c+ynV4Z9xNi8s9dkd+E9Ste5Vig4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-admin
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgAeqvkF07nYMPQe21gzsImmebAGZV0y3xLFhzqCzGRIDtkGDC6BweYZbkZz8GUvY1Wt3KDsZFGAJYzIFOIAcgr4Gl6Q7Uure3b1ryXQduBDqvpwurzvrwqpq/kVZbXRj1PqMKm0sSlTCEWEJRmDha8Rpp4BroQpnAXZg1O7kJKF8UPhErr/zwgYFBQplu4v9L3TLs/NgQ6+vLXilU17cYwFx8CMtGzzOD6D22iU7CG6eT0K8mHQDaUQV9TGv91A33kv1aQUoomtJAOFjuhI96VGaV+ZiUUMn2yH90wpdaxBE/eP1hhv7nzjNtth5ERw26+T7XU6wCBFV1Q0BS/jAlXbmH3yqRdj0SHcPOsW4s6QkRsxKR2RaZ8yIzYaih0F8ML7odCDkqdF+zz+f6rdqGDCEl1150eTnFq1lPBYvB1+NuKJ6H9bS3qMXy6SHFjhoRtRG/qWzSDsHUJSHzjJ3qcSRJuvdW4nhRSRnIZoElgVnVec6gzZYsmLM2lFk/ml3m1LBCGYdj6guQl9JSEMxSEV8Se4e7yw+xFxeOqtjophlVWcvx9MXy3rA2OKI0Gw+goJr21OzWoxWqtdL2tKf0s0VzOG3cNDPuPVq2objB3opmRxZYcNW0ZLV6cUA6T8Q3VIgIgrMZHfc0kP2M5GrxiaveqPhhwjvkshBM5/kJR4TEkPAo3QdF/DmGIzlvaMV0nxh/VajdTrNfvpan3OayNW9SoNvwpOfbg=
    nextcloud-token: AgAFtKYZbuiv92At2QBpjqe6UUD5tdzWBDhVHSe4daFDI74pWo8JrKVQY68pFbxeC3CEoj0GgmRJpYDhxsDpS1ld2zYzG+J7oMd6dbv5pNGB5wKFkE6CyZ1pXnHFnNMggxP1BZKMA7J5gENjfAfmltVr5PTkb0kdaTfM1lnecRYKLl7lfhItlfJ6s5XRVqjAvfVewIdn/2wqG6LCMHgQ0ifyRT7sYWepK1pc3Res/qqaP89bEeodOS1TjwvAAxdNwDx0yPKfVGPVCjDsvaNydhEF+j1hwBuLuh9GpO/XfQnKzh0BoaehXy883UCiT6JPyuXKI6dojJRx9JHA7O+P9OzklnKAXCGHgE0i6hsN/Orvida80OqZcIgDj+phxQoX9SqXsLWavUYiEwpkH5T6C4o0kJW+RWmg9s6wxLWZQ+X6PeVF2tSDTzosu8eyjVUCBDFT+I6GXWCf2/aNZkGTOXIA0qQPGQM5X8FcJn0ge5ubBxwguhukRTlumQyVCo1+9o77J1S4ln9lxMK/4LxZswFxkIQJCNtlWMYZXG6HT+/NYvZIf+Ufn9fMc5RQ84gIQUC97uDoeJ36ooFUiKGSdgwkIABpbFFyPMss4MCmG1tY6/snEbgBZKeZj47L52gWs55M093CqW4PG2YldIhZPGHI+Rng4ub5+Esnp/Tu/dSBFZDcBLAem7ni+PW+M14k2Yi+OKCxwKIJmSOMif0GVsdN
    nextcloud-username: AgCm5MjzyhGpVFu7KMMbXttxKYIswghuGtg2MXh3UdYFVzkaQCZ9+4jrdftJhqpbYAcFiGvGyZJuhjtgtBpI5kAHIJZHmBVHY9A7Fwg/iEEcGtJm9vDPWRICb+z31h7e7cb/oACkPcs5km6WtfQvju6u1K6xsn/EQX3Dlrw5CgvMU+cNe7uz21On1z4wl9hQWsMnq7zWOm7ypPE2Ku2FAJ16Ms7PaCVEI0JqJravtFITS6+dPuxGIRh85U4V2aZfKv/v/G3YTGgkFl/kUJs6W1JjHUxoZFT2eu3kFbmlCreIS23VoXf7SoHJFArqMCu7igWBrh1gdf2zSulxAYs++Q8FnCXijyUMOkWv1zy2qUy/Xe8sTDli3J6f0HTY3BeZR645knl9ie1DGAz++HbPKCMYuDRzZgqf8LgH2gXBunXh9UaRz3MLe5855RHQxx+TehqvXMtnk9zdDOeSad6NriRpwon+lB7I7o12MQfDM+R8j2KXstEUSZ1J3lcG8jlgaB+XP7VlbIUim9wPGIeXaklTVBFFqhpjCrF9Gz/vSjEnmpRBbtIuS2WIhM/p9vRAPcPzAlDCsPEM+KPAf5Wp6WLKS2B3NvevYnNtLhy8owzP+ekji81Rd2cEJ17D/jaHxxKY6hhkXRX3cFRkS4apaLOmZCzDxu1GZTSdA2OgiOFNEhYhTcc7Cw9GQNp7Qdj+Hi8nSviKJwVL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nextcloud-admin
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secrets
  namespace: nextcloud
spec:
  encryptedData:
    password: AgChde5owT/b6nC1fDOYU+K38h0Z9iIeWj5vW01v6ZQXVkxTTWw7ckEOfpVuA5M7+HsVq8KoIlAhwvYm/2CPhze4Ft0lWnTRGH8BtP9TxKNa5K8dPXTRyzDaCsXHP/wYvI8gX4Sz5mGSk9MPFuZfmNnfziyL21qeDiA+6X79ctzET3nFgiKq/Kh/b6ZGw+MciLC+7qOchNbsqmPQdh0dAP2eIjRS7i8QDXsRgMc3ay51EOMhnhLxNK08gtdL29nNhSPXuOSJk6r8iLl3hTfpf5cqvlBNHA62Lv8cjRWcOohQqbQNV1cBzWz22SIiSGtYpb3N54ebzoxQjohduzbhqOKcTtGk5ee0T1niUuIYTAJXF//OshGADtMZC4n70+m38UWDqG6n1Yy1hQQ1+g9ON8mTbaxv9PSyx2Jw40hwh0a7mwNXsTrRroyovlIyhLX+fKXnF/dun8KIZ/P5pCc1mOqArn+OiqaoCZUjkKPI16RuyrMozejDgOsvBZtMsxxaGZhxE7fMhIyrGin68k0uMyoGfIjj9Q14oz2AZnhp6MJfFlixOM4o82bb1mLAqjHpXHu8uRiryp8lHZznpAOq4l8RoJGjoeGEx+N6JrPX70PKEkzlXuWu1cCEhZVKYAnnseceFhimV8cvieXIP0tSgphdxuZTyZrZIblQOiD20uSOHN40AsoZ8l0Q16BIJpxYaCjxOMtzWVF3GWRuUG3jGf8khYk=
    postgres-password: AgCH0ZV+Iz0eWmC8OwoYHKAv5KBtWeeAOZs754FuJxqGWfuzP08YU/EpKgebksdBO4nz7oC7zFW1RciGfvx7/pDfVVgEBMXkN7SMwrzQ9AKQVpx+15Uz0MFXQlK3kFLiAYoK0lQF+bHYAuStgjD6i60xoAr8HXvZAQhyONpFyWWVjhK9uGLlSlGJjaKYDdBZxoFmqQeFS27Q6NQFMZf/aHAb46gav5TquPpR4B2zdNuwMftTRYCu5ktz5A/uvMA63tOIE5UvHMAbqtdvG/SOsdgNywUWGnP11ftqY8aTa4QMPN1StmdUanCe8l/7svjKjZr3sA2r5O7+p2pEMHOXN0++phw4En6sPPywzi4UBn0WOxSkyhEhiDcnfNOPgHPcHazpIcZGtZ+YcHBevG5IgFEQbyZyNFsIS7aEWA8ZNerMwQMbvQmzJ9IW/FJFvWcurZYMGu2jl6PtOykCjXltZBzjQuv5JvI4Q1AMPD/9O287YgTd8OEo7rGne+KfFvUetdpHenTuKwwifl8721cawAzd7ZWJXhszZWyIJiH2dmhy2DxSyHFoj50xGdUxfpfegV7yVvDfLZ8ktlIDn0gzEsmo0yUXaG57VWTPSifMPpImY0mLQRQY3nqntwE7F2c1tShe6W3R4E9xCsyJ73VNq8yEMpnX1FZkmxLJ1yrvQVnoD2tJTTB2ZGdOEsE4lMq4b80q/LY4S50L+WFd/XHDmUUk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgresql-secrets
      namespace: nextcloud
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: externaldatabase-secrets
  namespace: nextcloud
spec:
  encryptedData:
    db-password: AgAP9jSAgzDhrrpElOdBkZDdU4Qd47dNduC9LO5e6ZXLgJ4NAuG7BZvahGx1q00OlHAp/rEFZyEale/4KO3oVkdeEnFxZWAQFG0e8TJywWS0YCHQSS1ZJUlsRP1ItGcpribNPB1tEFsIeIV88kVSKEGUy+I2VD9j+16ExJjipRTlS3GY//TpkG5mB9n0jgvsxPYVY91EIcHqXGrxrlji9pCN6AOUEJh3OfKdr8VjNWpG+MsqrBgr2OsRjuUuZ0gMh7YCMJulEa5UzLmo+FgosEc7Aah2FGVGDIbxRIZHnyxBFydByotWHQc22NuwZfQCk2+mYxXcMVdqgrgzyZSPPUNPALdplWhWLmtUce4RMcq+cKDX1LYdCJCU50Uorrp0LFiIBLBRzTKkz/zzsR0jjxpU1NavRsEGcpbGMACH51KM606JiJ/a86JADyFkO+e0VEbTmtTmgNAW4NloizReQorlHJiSItwHTDNMlufECjSryRwcfMe4KuRz1ZLkD1D4eYzglkPuufr6BkxKb8RcFGCHVwbJxekJ5Otlq6x1kKh6+y5cG4wYnj4QpN/YiDK6+tRFLJ6rSdwVqk8GkzSPLBhov2QFmzjRHH9LqdJqS9z2YERYbXTQUkbJxzyFO0FRjSO+dGihfPf/TRRC9TUl+3Zhqxm7bJ8pbCJmaTJ+mWZa4ILIqf6JZtf7+IZk5p1dV0zJNshWDWcfGvgEQMj1hjNGiRcixZRvtKg=
    db-username: AgAzmaGzq22b+p6OLBQU6iUEIjx5FONP5T+5GOxTXKFQ6VVO/710jSHYBLHnm9sep0UmTfdEULTMhM94U7ARZM3VuseHJZIGPRbnyU19UngDP7xUW4Byktd8GzOvLBeBGVPHeahoPE132ILoQ4XRMsM34j3gYavVofvdHeUTB1IUExiVmbpEAJ+Cs3jmOaOFzvuJR27hlDaYubcTealTMZQYP5hUQnvxrlds6nLtUArZ7DRvqe/WvXwXkhxqCHGUT7Ysi+MkUqNjY6KbiBMQrIe0H8fFVxZxfcEHQGYmbY8qfHoLLi96Mapg/J6XnUFxWKsJh+FmHybBMJPhNhIML+usZ3brJbkaF7NpjsVr1ndjI1BUoZKoh3NX5KK4h69p8fArXrylROKzahO+YOS0KvCZgL0/adagXiLwTQe3zAI+wK+CeE8eLODuP+7rP+f9HbEoNTceq5PzbuDDRZjeA5RBEs0F9G0Vdzi3rhTfS+VFz+S0/q9qHMcmY2nalMxO3HNNoabmId6lEDuculEwEbhqkoHBcBHUmw6aaiM50Y92qC8zDvLa5wbeGAyuSCO7E+Cheu2qkoGB6D3i9xfEENuZWptK/QWZg8+fkbId8jPGJ0d3q/Gqj0rF+eR0v+lkKMivYAmv+2ZnAQi0P6RLM7QQlTGOlO9AimubYmkFRmA6VYTyGah07Anv0A1yt6ooocv6GUqTfqhxS8A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: externaldatabase-secrets
      namespace: nextcloud
    type: Opaque
