apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgA/7SLtqVXz0LhtEEAOtuUGXkDIb83y1sc6WP5RszSDQohkK1K6fIMB9fhHJWftcKJBzarq+OPRL/b7bH7VnY43TfJAnavVRnc4s42oNBmQjrZ2A+R+L5wiHh81eYI6VWobAw4CvhIOtiaRzLU3REazOQKbQ+U/fEQUOt3W3HU68OJtf/JVuP0Tk/+Q1k1M/21KD1+xShZTkmEzaqYWmnPBNYpTfxCA038CKui8vKrMwPj9StAA2Ch3KEAu44f+dUSIObEWXSVbYkozz81Kvv9rDyWEY85B5CaWMGhc/gW/xlR9R8mnrVtlmpAGVq2/fdBMMtQXfYSs5oQO+73NfAwb5ZacYktdGjAlekzWrYsPmYZmZIk4CN25V8KTkYL9fvu8/U7DNGVfFLyIhf6js9bP7DDQlQZPCIWaU0/Vn3Qk+ErB+X/CeobOSr73MB7u4F4FEcw/s/lpzSA11JmLVLwQ6410QEpEEiYci/7eaJWaDepyV+QTDGAPHP/UNZcTVxtabHEmA56c3YTymxDRO/Ws8a7eElf7ZrK33EWpl+o4T8g6zXgE8ox6+xDAD+qhA2GQBSFhMjDy90s7mGyhw/TeXw3jG95qEeXA72rBFAUlimbz0qGoZYyd+T53QrkpOrn6aTxgEon26LWg2JSz4Zv8MRs/9z8LEE1BvUzb9YoiMsGP/XQtQuI64ISA4PWqHKlB1+DmEmzjAVYM72+acdkQIElhN9CnANIA18L6d/xdY2cl21jlWaLGq4xFrTxxfDZw/njhTaHdyLN8zGXkkvAqPyvhTBDtbxu4bL1dv1hA3zeTzUdhK6KvQpQwUwDkyuWylgGnfvSP4YiPfxXiexLLCf57wPepyQdAuUbBOBcliXiaDSC2O8cCsN1Gyq5BthlG+OzeWY3Vj1+LIVthcB5BeB2bPjUhG+5tABphoyoVXnlHNrcKYY7gKSxQ3z4Dv13dCqF7Zk0ssfrruy5HBdYIS5idDtGnSR2wSlB3v8wm/kxMTXC5M5Ln9Wa5vIq0jPiExQu++WsGY09dZsT6z+MvtL4kFPfS2rum5Bhj4ugwF0/jKq+2aRLH1MCoZ3pZaTuGwu/pbkIadP3khVuAAEd8RMgwFbalB2a5d62V9IddofW5CCWD2WKmYgNDdynTNhWC7Apmgkw2ELP5CJD4rn/vi/5AGA9XP1TYLRHABj+oUPVpNBGAhuFQMqXki+YNq8znWdsfzUmv948ikkjt2ec=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

