apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nextcloud
spec:
  storageClassName: longhorn
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/lib/data/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nextcloud
  namespace: nextcloud
spec:
  storageClassName: longhorn
  volumeName: data-nextcloud
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
