apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.13
      sourceRef:
        name: ingress-nginx
        kind: HelmRepository
  values:
    controller:
      image:
        registry: k8s.gcr.io
        image: ingress-nginx/controller
        tag: "v1.1.0"
