apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-music
spec:
  storageClassName: longhorn
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/music
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  namespace: jellyfin
spec:
  storageClassName: longhorn
  volumeName: jellyfin-music
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-youtube
spec:
  storageClassName: longhorn
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/youtube
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube
  namespace: jellyfin
spec:
  storageClassName: longhorn
  volumeName: jellyfin-youtube
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-books
spec:
  storageClassName: longhorn
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/books
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books
  namespace: jellyfin
spec:
  storageClassName: longhorn
  volumeName: jellyfin-books
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-movies
spec:
  storageClassName: longhorn
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/movies
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: jellyfin
spec:
  storageClassName: longhorn
  volumeName: jellyfin-movies
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-shows
spec:
  storageClassName: longhorn
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/shows
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shows
  namespace: jellyfin
spec:
  storageClassName: longhorn
  volumeName: jellyfin-shows
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
