apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: registry
spec:
  encryptedData:
    auth: AgADV3UJUEsj51XEPEYYmZ5ffoLZly6awLUa0opM5yojgy6bBFp2wKzomHnYcMmm62Oza9aaIbn8cIyqheZXkyjexZULI+s2zWLTgPA9vCKfj5wwqhEEG7uhDhr5a7pcaQ+jadcUX1WzZuunOqAszsAKbNuEEJO5ro4x+xVKkh/F5Uvgeo92UOuPh8BhL1MQ6z0dRBAvqnGYeGBsYNRLI8/1gRzwUN7zMVdUY3hXT3w1G2knvMx0txfe4RBWir43sME7CrlVMY56JSjdYkiG7O93FCNVijky1/gzNCToSHoXk935MVO/Gsi4T3UxOn19XW6xLdQQTYXFolLMgpaVtO0dOluU8EBtCjifBw61Ba2P+lGi6w8Oqy2aoOe8TYcA7+27UOHOeTb26QSHYnZLjMCfOwZJVCSZd1GGiZMXYb2X3belTmvAtehWBd0CG6JtUvhGPKD/HtQ9y2QGYPMHs+DB1rehZKrcZfrMuwAgHM7Vu5BDuwYzWcVTe91jXYaymN0U2kgWTdtjTLK5wQV3Q9yssSEZeDQsVgsgiByYAph82D85EPuN37lqhb/ZA6VEOALpiSSV719pYF0iWI7fiNRVQSGLMc5nEHuW++ST6L29K9qLTyUVFlaGPOJ3v1SNS7HZoQbQd6ziTxBLqV5OI6JkD4oyaCuW+twZx8EwODag2qRisqGP2RZMy04F7qeDOe0PoPdDkTcXzDVEpzhg1Vlt46sJEEhySi6V/HW5rat8VITfz/kOreWjw8p0Fww+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: registry
    type: Opaque

