apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgCSW7ulIBf8N4bM6su7cjeSpVkILZ9eBWs7F1nRJRFSspvrlJhS8X+5bobc0Sit0c2hjQ6t/4OlEW+zPnnsBflDXt0SBx2WNNx2coJe1utd6bYl71AHoP6rXIOu725jJCzKD7pUL3B+3PrEXG2zIOgmlPaRn8dQw+7uWFrT//e+mzfPTYf8b020qdk5rlgzaTQIo51uBe0drhJRZmbUUVpH80QqvLvh0PtHPvV376Ejzc2LGapzfxzVzE5+iZFCLtLdcg74Yoo8phgsbjh/ix5A9KzCR07p7jDh+IeTpzxcLg1E1FT2GSBMA8NpWrNeQs4QHX72WAyVHpoXyILJE524YQREfY+ebabOxD0mfKtcSNR8oCpLW+tSZC3sy5QNaBJTw1EjWEZ86lE9jZDrpc/7UqH5fyG5+W9W5RDXmce3xCUrExVQzF0S43qYaNc/hZZPR8vaY7Ndc/+y6tRYL2dnfSB04HohIrLDUr9XR7fZyKsHLGMvEh+oZac1CMhJ+a6eL07whrMqe4+BuDrKGSTcN0LytHaCocf6ukDc8tMtAQY1T0i/HoEK6Duv/iV0YYKqEP5FmLS2XkTtwy4ssd9ncAFvM6jUOD1XunzqZSa90dLfr/qXxJVT7kx+M2Ef9WBYfwSVUiein1Nw67Dpa3/ZAAWC2FAUkNWWH7+sSsYYBUBgztWsePptXqvbw6Gz9jLOOZqmqzh4xwBx9P1/7LIzsYP13keU+cmwhkKlrifGlcX7jeio2SrWFJDGhFVo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system
    type: Opaque

