apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.2.3
      sourceRef:
        name: longhorn
        kind: HelmRepository
  values:
    image:
      longhorn:
        engine:
          repository: longhornio/longhorn-engine
          tag: v1.2.3
        manager:
          repository: longhornio/longhorn-manager
          tag: v1.2.3
        ui:
          repository: longhornio/longhorn-ui
          tag: v1.2.3
        instanceManager:
          repository: longhornio/longhorn-instance-manager
          tag: v1_20211210
        shareManager:
          repository: longhornio/longhorn-share-manager
          tag: v1_20211020
        backingImageManager:
          repository: longhornio/backing-image-manager
          tag: v2_20210820
      csi:
        attacher:
          repository: k8s.gcr.io/sig-storage/csi-attacher
          tag: v3.2.1
        provisioner:
          repository: k8s.gcr.io/sig-storage/csi-provisioner
          tag: v2.1.2
        nodeDriverRegistrar:
          repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
          tag: v2.3.0
        resizer:
          repository: k8s.gcr.io/sig-storage/csi-resizer
          tag: v1.2.0
        snapshotter:
          repository: k8s.gcr.io/sig-storage/csi-snapshotter
          tag: v3.0.3
    persistence:
      defaultFsType: btrfs
      defaultClassReplicaCount: 1
    ingress:
      enabled: true
      ingressClassName: ingress
      host: longhorn.ssene.ca
      tls: true
      tlsSecret: longhorn-tls-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
        nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      backupTarget: nfs://10.0.0.2:/srv/nfs/backups
      defaultReplicaCount: 1
